package br.com.avaliacao_lp2.view;

import br.com.avaliacao_lp2.dto.AdminDTO;
import javax.swing.JOptionPane;
import java.awt.Image;
import java.awt.Graphics;
import javax.swing.ImageIcon;

/**
 *
 * @author sassmatheus
 */
public class MainVIEW extends javax.swing.JFrame {
    
    public MainVIEW() {
        initComponents();
        this.setLocationRelativeTo(null); //centraliza main
        this.setTitle("LP2S4");
    }

    MainVIEW(AdminDTO adminDTO) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    
    private void sair() {
        Object[] options = {
            "Sair", "Cancelar"
        };
        if (JOptionPane.showOptionDialog(null, "Deseja sair do Sistema?", "ATENÇÃO",
            JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE, null, options, options[0]) == 0) {
            System.exit(0);
        }
    }

    private void abreAlunoVIEW() {
        AlunoVIEW alunoVIEW = new AlunoVIEW();
        this.desktopPane.add(alunoVIEW);
        alunoVIEW.setVisible(true);
        alunoVIEW.setPosicao();
    }

    private void abreCursoVIEW() {
        CursoVIEW cursoVIEW = new CursoVIEW();
        this.desktopPane.add(cursoVIEW);
        cursoVIEW.setVisible(true);
        cursoVIEW.setPosicao();
    }

    private void abreMatriculaVIEW(){
        MatriculaVIEW matriculaVIEW = new MatriculaVIEW();
        this.desktopPane.add(matriculaVIEW);
        matriculaVIEW.setVisible(true);
        matriculaVIEW.setPosicao();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ImageIcon imageicon = new ImageIcon(getClass().getResource("images/tela_inicial.jpg")); Image image = imageicon.getImage();
        desktopPane = new javax.swing.JDesktopPane(){ public void paintComponent(Graphics graphics){ graphics.drawImage(image, 0, 0, getWidth(), getHeight(), this); } };
        menuBar = new javax.swing.JMenuBar();
        menuCadastrar = new javax.swing.JMenu();
        itemMenuAluno = new javax.swing.JMenuItem();
        itemMenuCurso = new javax.swing.JMenuItem();
        menuGerenciar = new javax.swing.JMenu();
        itemMenuMatricula = new javax.swing.JMenuItem();
        menuSobre = new javax.swing.JMenu();
        menuSair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuBar.setName(""); // NOI18N

        menuCadastrar.setMnemonic('f');
        menuCadastrar.setText("Cadastro");

        itemMenuAluno.setMnemonic('o');
        itemMenuAluno.setText("Cadastro Alunos");
        itemMenuAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuAlunoActionPerformed(evt);
            }
        });
        menuCadastrar.add(itemMenuAluno);

        itemMenuCurso.setMnemonic('s');
        itemMenuCurso.setText("Cadastro Cursos");
        itemMenuCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuCursoActionPerformed(evt);
            }
        });
        menuCadastrar.add(itemMenuCurso);

        menuBar.add(menuCadastrar);

        menuGerenciar.setText("Gerenciar");

        itemMenuMatricula.setText("Matrículas");
        itemMenuMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuMatriculaActionPerformed(evt);
            }
        });
        menuGerenciar.add(itemMenuMatricula);

        menuBar.add(menuGerenciar);

        menuSobre.setText("Sobre");
        menuSobre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuSobreMouseClicked(evt);
            }
        });
        menuBar.add(menuSobre);

        menuSair.setMnemonic('h');
        menuSair.setText("Sair");
        menuSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuSairMouseClicked(evt);
            }
        });
        menuBar.add(menuSair);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 676, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuSairMouseClicked
        sair();
    }//GEN-LAST:event_menuSairMouseClicked

    private void itemMenuAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuAlunoActionPerformed
        abreAlunoVIEW();
        // TODO add your handling code here:
    }//GEN-LAST:event_itemMenuAlunoActionPerformed

    private void itemMenuCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuCursoActionPerformed
        abreCursoVIEW();
    }//GEN-LAST:event_itemMenuCursoActionPerformed

    private void itemMenuMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuMatriculaActionPerformed
        abreMatriculaVIEW();
    }//GEN-LAST:event_itemMenuMatriculaActionPerformed

    private void menuSobreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuSobreMouseClicked
        JOptionPane.showMessageDialog(null, "\nAplicação desenvolvida como requisito avaliativo."
                                          + "\nDisciplina: Linguagem de Programação 2."
                + "\n\n                      Matheus Sass"
                + "\n                         IFSP / 2022");
    }//GEN-LAST:event_menuSobreMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuItem itemMenuAluno;
    private javax.swing.JMenuItem itemMenuCurso;
    private javax.swing.JMenuItem itemMenuMatricula;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuCadastrar;
    private javax.swing.JMenu menuGerenciar;
    private javax.swing.JMenu menuSair;
    private javax.swing.JMenu menuSobre;
    // End of variables declaration//GEN-END:variables

}
